# Generated by Django 5.1.15 on 2026-09-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text='Optionnel (sinon le thème de la séance).', max_length=250)),
                ('date_debut', models.DateTimeField()),
                ('duree_h', models.DecimalField(decimal_places=1, default=1.5, max_digits=4)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('hybride', 'Hybride')], default='en_ligne', max_length=12)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('confirme', 'Confirmée'), ('realise', 'Réalisée'), ('reporte', 'Reportée'), ('annule', 'Annulée')], default='planifie', max_length=12)),
                ('note', models.CharField(blank=True, help_text="Ex. motif d'un report.", max_length=300)),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='formation.seance')),
            ],
            options={
                'verbose_name': 'Événement (séance datée)',
                'verbose_name_plural': 'Agenda (événements)',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('agenda', 'Agenda'), ('rappel', 'Rappel'), ('info', 'Information')], default='info', max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='agenda.evenement')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField(help_text='Date de la première semaine (le calendrier en découle).')),
                ('active', models.BooleanField(default=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_encadrees', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Vide = un seul jour.', null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('promotion', models.ForeignKey(blank=True, help_text="Vide = s'applique à toutes les promotions.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='agenda.promotion')),
            ],
            options={
                'verbose_name': 'Indisponibilité (jour non travaillé)',
                'verbose_name_plural': 'Indisponibilités (jours non travaillés)',
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='agenda.promotion'),
        ),
    ]
