# Generated by Django 5.1.15 on 2026-10-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_role_formateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(blank=True, help_text='Vide = message automatique de la plateforme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cible', models.CharField(choices=[('tous', 'Tous les utilisateurs'), ('apprenants', 'Tous les apprenants'), ('formateurs', 'Tous les formateurs'), ('promotion', "Les apprenants d'une promotion"), ('personnes', 'Des personnes choisies')], max_length=12)),
                ('par_email', models.BooleanField(default=False, verbose_name='Envoyer aussi par e-mail')),
                ('nb_destinataires', models.PositiveIntegerField(default=0)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_envoyees', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='agenda.promotion')),
            ],
            options={
                'verbose_name': 'Notification envoyée',
                'verbose_name_plural': 'Notifications envoyées',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agenda.annonce'),
        ),
    ]
