# Generated by Django 5.1.15 on 2026-10-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_notifications_envoyees'),
        ('formation', '0004_alter_ressource_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='ouverture_auto',
            field=models.BooleanField(default=True, help_text="Chaque module s'ouvre le lundi de la semaine de sa première séance. Sinon, le formateur ouvre les modules un à un.", verbose_name='Ouverture automatique des modules'),
        ),
        migrations.CreateModel(
            name='AccesModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('auto', 'Automatique (calendrier)'), ('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='auto', max_length=8)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='formation.module')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_modules', to='agenda.promotion')),
            ],
            options={
                'verbose_name': 'Accès à un module',
                'verbose_name_plural': 'Accès aux modules',
                'unique_together': {('promotion', 'module')},
            },
        ),
    ]
