# Generated by Django 5.1.15 on 2026-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_promotion_ouverture_auto_accesmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code_vitrine',
            field=models.SlugField(blank=True, help_text='Identifiant de la session sur le site vitrine (ex. teledetection-sig-initiation) : les candidatures reçues pour cette session sont rattachées à cette promotion.', max_length=100, verbose_name='Code session (site vitrine)'),
        ),
    ]
