# Generated by Django 5.2.18 on 2026-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_candidatures_vitrine'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='date_affichage',
            field=models.CharField(blank=True, help_text='Ex. « Tous les samedis ». Vide = la date de début (ex. « 14 octobre 2026 »).', max_length=60, verbose_name='Date affichée'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_vitrine',
            field=models.TextField(blank=True, help_text='Deux lignes affichées sur la carte. Vide = la description de la formation.', max_length=400, verbose_name='Résumé (vitrine)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='domaine',
            field=models.CharField(choices=[('Socle', 'Socle'), ('Urbanisme', 'Urbanisme'), ('Démographie', 'Démographie'), ('Paysager', 'Paysager'), ('Numérique', 'Numérique')], default='Socle', help_text='Sert au filtre du catalogue.', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='duree',
            field=models.CharField(blank=True, help_text='Ex. « 5 jours », « 4 samedis ».', max_length=60, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='horaire',
            field=models.CharField(blank=True, help_text='Ex. « 08h – 16h ».', max_length=60),
        ),
        migrations.AddField(
            model_name='promotion',
            name='lieu',
            field=models.CharField(blank=True, help_text='Ex. « Abidjan, Cocody » ou « En ligne (visioconférence) ».', max_length=120),
        ),
        migrations.AddField(
            model_name='promotion',
            name='mode',
            field=models.CharField(choices=[('En ligne', 'En ligne'), ('Présentiel', 'Présentiel'), ('Hybride', 'Hybride')], default='En ligne', max_length=12),
        ),
        migrations.AddField(
            model_name='promotion',
            name='places_hors_plateforme',
            field=models.PositiveIntegerField(default=0, help_text='Inscrits reçus par e-mail, téléphone… Les inscrits de la plateforme sont comptés automatiquement.', verbose_name='Places déjà attribuées hors plateforme'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='places_total',
            field=models.PositiveIntegerField(default=20, verbose_name='Places au total'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='prix',
            field=models.CharField(blank=True, help_text='Ex. « 150 000 FCFA ».', max_length=60),
        ),
        migrations.AddField(
            model_name='promotion',
            name='publiee_vitrine',
            field=models.BooleanField(default=False, help_text='Affichée dans le catalogue des sessions de 2kpinnov.org, ouverte aux inscriptions.', verbose_name='Publiée sur le site vitrine'),
        ),
    ]
