# Generated by Django 5.0.6 on 2026-09-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=250)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre'],
                'unique_together': {('formation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mercredi', 'Mercredi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('theme', models.CharField(blank=True, max_length=250)),
                ('duree_prevue_h', models.DecimalField(decimal_places=1, default=1.5, max_digits=4)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='formation.module')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['module__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('notebook', 'Notebook (.ipynb)'), ('lien', 'Lien')], default='lien', max_length=12)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('url', models.URLField(blank=True)),
                ('colab_url', models.URLField(blank=True, verbose_name='Lien Google Colab')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='formation.module')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='formation.seance')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('libelle', models.CharField(max_length=300)),
                ('niveau_vise', models.PositiveSmallIntegerField(default=3)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='formation.module')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['module__ordre', 'code'],
                'unique_together': {('module', 'code')},
            },
        ),
    ]
