# Generated by Django 5.1.15 on 2026-10-01 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_seance_parametrable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressource',
            options={'ordering': ['ordre', 'id'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.AddField(
            model_name='ressource',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_deposees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ressource',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ressource',
            name='instructions',
            field=models.TextField(blank=True, help_text='Ex. : « Décompresser puis ouvrir le projet QGIS ».', verbose_name="Consignes d'utilisation"),
        ),
        migrations.AddField(
            model_name='ressource',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='fichier',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='ressources/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('notebook', 'Notebook (.ipynb)'), ('code', 'Script / code'), ('archive', 'Archive (zip, rar…)'), ('document', 'Document'), ('presentation', 'Présentation'), ('donnees', 'Données (CSV, SIG, raster…)'), ('image', 'Image'), ('video', 'Vidéo'), ('lien', 'Lien'), ('autre', 'Autre fichier')], default='lien', max_length=12),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url',
            field=models.URLField(blank=True, verbose_name='Lien'),
        ),
    ]
