# Generated by Django 5.1.15 on 2026-10-01 15:25

import apps.core.stockage
from django.db import migrations, models


def _vers_prive(app, modele):
    def deplacer(apps, schema_editor):
        """Déplace les fichiers déjà déposés de MEDIA_ROOT vers PRIVATE_ROOT (plus servis publiquement)."""
        import shutil
        from pathlib import Path
        from django.conf import settings
        Model = apps.get_model(app, modele)
        for obj in Model.objects.exclude(fichier="").exclude(fichier__isnull=True):
            src = Path(settings.MEDIA_ROOT) / obj.fichier.name
            dst = Path(settings.PRIVATE_ROOT) / obj.fichier.name
            if src.exists() and not dst.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dst))
    return deplacer


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_ressources_tous_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='fichier',
            field=models.FileField(blank=True, max_length=255, null=True, storage=apps.core.stockage.stockage_prive, upload_to='ressources/%Y/%m/'),
        ),
        migrations.RunPython(_vers_prive("formation", "Ressource"), migrations.RunPython.noop),
    ]
