# Generated by Django 5.0.6 on 2026-09-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('apprenant', 'Apprenant'), ('formateur', 'Formateur'), ('admin', 'Administrateur')], default='apprenant', max_length=20)),
                ('structure', models.CharField(blank=True, max_length=200, verbose_name='Structure / Université')),
                ('specialite', models.CharField(blank=True, default='Géomatique / Bases de données spatiales', max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_gee', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='Compte Google Earth Engine validé')),
                ('compte_github', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='Compte GitHub / GitLab créé')),
                ('miniconda', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='Miniconda + JupyterLab installés')),
                ('qgis', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='QGIS (version LTR) installé')),
                ('git', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='Git installé')),
                ('machine', models.CharField(choices=[('ok', 'OK'), ('en_cours', 'En cours'), ('a_faire', 'À faire')], default='a_faire', max_length=10, verbose_name='Machine ≥ 8 Go RAM, connexion internet')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Prérequis',
                'verbose_name_plural': 'Prérequis',
            },
        ),
    ]
