# Generated by Django 5.1.15 on 2026-10-01 09:35

from django.db import migrations, models


def formateur_vers_enseignant(apps, schema_editor):
    apps.get_model("comptes", "Profil").objects.filter(role="formateur").update(role="enseignant")


def enseignant_vers_formateur(apps, schema_editor):
    apps.get_model("comptes", "Profil").objects.filter(role="enseignant").update(role="formateur")


def superutilisateurs_admin(apps, schema_editor):
    """Les super-utilisateurs existants deviennent « Administrateur »."""
    apps.get_model("comptes", "Profil").objects.filter(utilisateur__is_superuser=True).update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], default='apprenant', max_length=20),
        ),
        migrations.RunPython(formateur_vers_enseignant, enseignant_vers_formateur),
        migrations.RunPython(superutilisateurs_admin, migrations.RunPython.noop),
    ]
