# Generated by Django 5.1.15 on 2026-10-01 10:10

from django.db import migrations, models


def vers_formateur(apps, schema_editor):
    apps.get_model("comptes", "Profil").objects.filter(role="enseignant").update(role="formateur")


def vers_enseignant(apps, schema_editor):
    apps.get_model("comptes", "Profil").objects.filter(role="formateur").update(role="enseignant")


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_roles_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('formateur', 'Formateur'), ('admin', 'Administrateur')], default='apprenant', max_length=20),
        ),
        migrations.RunPython(vers_formateur, vers_enseignant),
    ]
