# Generated by Django 5.1.15 on 2026-10-01 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_role_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Présentation'),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.FileField(blank=True, upload_to='profils/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='specialite',
            field=models.CharField(blank=True, default='Géomatique / Bases de données spatiales', max_length=200, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
    ]
