# Generated by Django 5.1.15 on 2026-10-01 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_candidatures_vitrine'),
        ('comptes', '0005_groupe_administrateurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=40, verbose_name='Téléphone')),
                ('participants', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('session_code', models.CharField(blank=True, max_length=100, verbose_name='Code session vitrine')),
                ('session_libelle', models.CharField(blank=True, max_length=250, verbose_name='Session demandée')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='nouvelle', max_length=10)),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='agenda.promotion')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_reception'],
            },
        ),
    ]
