# Generated by Django 5.1.15 on 2026-10-01 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='2KPI', max_length=60, verbose_name='Nom')),
                ('suffixe', models.CharField(blank=True, default='Learn', max_length=30, verbose_name='Suffixe (accent)')),
                ('logo', models.FileField(blank=True, help_text='PNG, JPG, WEBP ou SVG, idéalement carré. Vide = pictogramme par défaut.', upload_to='parametres/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])], verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, default='Knowledge · Key · Planning · Innovation', max_length=120, verbose_name='Signature (pied de page)')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contact')),
                ('image_connexion', models.FileField(blank=True, help_text='Format paysage (≥ 1600 px de large). Vide = image par défaut.', upload_to='parametres/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Image de fond')),
                ('titre_connexion', models.CharField(default='Apprends en pratiquant, progresse en continu.', max_length=120, verbose_name='Titre')),
                ('texte_connexion', models.TextField(default='La plateforme de formation pratique de 2KPI : cours, séances, quiz et suivi de progression au même endroit.', verbose_name="Texte d'accroche")),
                ('extensions_autorisees', models.TextField(default='pdf, ipynb, py, r, zip, rar, 7z, tar, gz, tgz, docx, doc, xlsx, xls, csv, pptx, ppt, odt, ods, odp, txt, md, json, geojson, kml, kmz, gpkg, shp, dbf, shx, prj, tif, tiff, png, jpg, jpeg, webp, qgz, qgs, mp4', help_text='Séparées par des virgules, sans point.', verbose_name='Extensions autorisées')),
                ('taille_max_mo', models.PositiveIntegerField(default=100, verbose_name='Taille maximale (Mo)')),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
